// English source catalog. New user-facing strings should be added here first
// (with their default English text) and to `src/lib/i18n-strings.ts` if they
// need typed access. Translations for the other seven locales live alongside
// this file — each one exports the same shape and is loaded on demand by
// `activateLocale()` in `src/lib/i18n.ts`.
//
// Message shape follows `@lingui/core`'s runtime catalog format: a plain map
// of message id → translated string. Ids match the `id` prop on `<Trans>`
// or the argument to `i18n._()`. Missing ids fall through to the default
// text provided at the call site, so partial translations are always safe.

export const messages: Record<string, string> = {
  // Bottom tabs
  "tabs.vault": "Vault",
  "tabs.security": "Security",
  "tabs.add": "Add",
  "tabs.profile": "Profile",

  // Profile — section labels
  "profile.section.account": "Account",
  "profile.section.appearance": "Appearance",
  "profile.section.language": "Language",
  "profile.section.session": "Session",
  "profile.section.danger": "Danger zone",

  // Profile — rows
  "profile.displayName": "Display name",
  "profile.displayName.empty": "Not set",
  "profile.email": "Email",
  "profile.theme": "Theme",
  "profile.language": "Language",
  "profile.signOut": "Sign out",
  "profile.signOut.description": "You'll need to sign in and unlock again",
  "profile.delete": "Delete account",
  "profile.delete.description": "Erase your account, codes, and passphrase forever.",
  "profile.delete.busy": "Deleting account…",

  // Appearance sheet
  "appearance.system": "System",
  "appearance.system.description": "Follow your device.",
  "appearance.light": "Light",
  "appearance.light.description": "Warm cream, always.",
  "appearance.dark": "Dark",
  "appearance.dark.description": "Easy on the eyes.",

  // Language sheet
  "language.title": "Language",
  "language.system": "System",
  "language.system.description": "Follow your device.",

  // Vault page
  "vault.title": "Your codes",
  "vault.subtitle.empty": "One-time codes, encrypted end-to-end.",
  "vault.subtitle.count.one": "{count} account · tap to copy",
  "vault.subtitle.count.other": "{count} accounts · tap to copy",
  "vault.section.favorites": "Favorites",
  "vault.section.all": "All accounts",

  // Security page
  "security.title": "Locks & recovery",
  "security.subtitle": "Everything protecting your codes lives here.",
  "security.section.vault": "Vault",
  "security.section.signIn": "Sign-in",
  "security.section.privacy": "Privacy",
  "security.section.session": "Session",
  "security.section.danger": "Danger zone",
  "security.passphraseHint": "Passphrase hint",
  "security.passphraseHint.empty": "No hint set",
  "security.autoLock": "Auto-lock",
  "security.changePassphrase": "Change passphrase",
  "security.changePassphrase.description": "Rotate your master key without re-adding accounts",
  "security.recoverySheet": "Recovery sheet",
  "security.recoverySheet.description": "Printable backup — accounts list + wrapped key QR",
  "security.encryptedExport": "Encrypted export",
  "security.encryptedExport.description": "Download a passphrase-protected .avf backup file",
  "security.biometric": "Biometric unlock",
  "security.hideCodes": "Hide codes",
  "security.hideCodes.on": "Codes stay masked. Tap an account to reveal or copy.",
  "security.hideCodes.off": "Codes are visible in the vault at a glance.",
  "security.lockNow": "Lock vault now",
  "security.lockNow.description": "Require your passphrase to open again",
  "security.reset": "Reset vault",
  "security.reset.description": "Erase everything. This cannot be undone.",

  // Add account page
  "add.appbar": "Add account",
  "add.back": "Back",
  "add.hero.scan": "Scan a code",
  "add.hero.manual": "Enter by hand",
  "add.section.codeType": "Code type",
  "add.section.account": "Account",
  "add.section.secret": "Secret",
  "add.section.tags": "Tags · optional",

  // Vault — account card / details sheet
  "vault.card.currentCode": "Current code",
  "vault.card.editingAccount": "Editing account",
  "vault.card.tapToReveal": "TAP TO REVEAL",
  "vault.card.tapToHide": "TAP TO HIDE",
  "vault.card.copyCode": "Copy code",
  "vault.card.copied": "Copied",
  "vault.card.nextCode": "Next code",
  "vault.card.autoGenerated": "Auto-generated",
  "vault.card.meta.algorithm": "Algorithm",
  "vault.card.meta.digits": "Digits",
  "vault.card.meta.period": "Period",
  "vault.card.storedOnDevice.title": "Stored on this device",
  "vault.card.storedOnDevice.description":
    "Secret stays inside your encrypted vault. Use Security → Export for a portable backup.",
  "vault.card.editingHint.title": "Editing account & tags",
  "vault.card.editingHint.description":
    "Service name and label update instantly. The TOTP secret is never changed here.",
  "vault.card.saveChanges": "Save changes",
  "vault.card.saving": "Saving…",
  "vault.card.edit": "Edit",
  "vault.card.remove": "Remove",
  "vault.card.removing": "Removing…",
  "vault.card.removeAccount": "Remove account",
  "vault.card.thisAccount": "this account",
  "vault.card.delete.title": "Remove {issuer}?",
  "vault.card.delete.description":
    "The encrypted secret will be deleted from your vault. You'll need the original QR or setup key to add it back. This can't be undone.",

  // Common actions
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.close": "Close",
  "common.retry": "Try again",
};
