/**
 * Push server functions (Phase 10.3).
 *
 * All functions are `requireSupabaseAuth`-gated — the caller is always
 * the current user, and RLS on `push_subscriptions` / `push_nonces`
 * scopes every read/write to `auth.uid()`.
 *
 * Flow:
 *
 *   registerPushSubscription  ─ user's browser opts in (once per device)
 *   requestApproval           ─ mint signed nonce + fan-out WebPush
 *   consumePushNonce          ─ verify signature + expiry, mark consumed
 *   unregisterPushSubscription
 */

import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { z } from "zod";
import {
  DEFAULT_NONCE_TTL_MS,
  signNonce,
  verifyNonce,
  type NonceMaterial,
} from "@/lib/push-nonce";

/* --------------------------------------------------------------------- */
/*  Register / unregister                                                */
/* --------------------------------------------------------------------- */

const RegisterInput = z.object({
  endpoint: z.string().url().max(2048),
  p256dh: z.string().min(1).max(512),
  auth: z.string().min(1).max(256),
  userAgent: z.string().max(512).optional(),
});

export const registerPushSubscription = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d) => RegisterInput.parse(d))
  .handler(async ({ data, context }) => {
    const { supabase, userId } = context;
    const { error } = await supabase
      .from("push_subscriptions")
      .upsert(
        {
          user_id: userId,
          endpoint: data.endpoint,
          p256dh: data.p256dh,
          auth: data.auth,
          user_agent: data.userAgent ?? null,
          last_seen_at: new Date().toISOString(),
        },
        { onConflict: "endpoint" },
      );
    if (error) throw new Error(error.message);
    return { ok: true } as const;
  });

const UnregisterInput = z.object({ endpoint: z.string().url() });

export const unregisterPushSubscription = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d) => UnregisterInput.parse(d))
  .handler(async ({ data, context }) => {
    const { supabase, userId } = context;
    const { error } = await supabase
      .from("push_subscriptions")
      .delete()
      .eq("user_id", userId)
      .eq("endpoint", data.endpoint);
    if (error) throw new Error(error.message);
    return { ok: true } as const;
  });

/* --------------------------------------------------------------------- */
/*  Request approval                                                     */
/* --------------------------------------------------------------------- */

const RequestInput = z.object({
  action: z.string().min(1).max(64),
  payload: z.record(z.string(), z.unknown()).default({}),
  /** Optional shorter TTL; capped server-side. */
  ttlMs: z.number().int().positive().max(DEFAULT_NONCE_TTL_MS).optional(),
});

function requireNonceSecret(): string {
  const s = process.env.PUSH_NONCE_SECRET;
  if (!s) throw new Error("PUSH_NONCE_SECRET is not configured");
  return s;
}

function approvalMessage(action: string) {
  switch (action) {
    case "approve_login":
      return { title: "Aegis · Approve sign-in", body: "Tap to review the new sign-in." };
    case "approve_export":
      return { title: "Aegis · Approve export", body: "Tap to confirm a vault export." };
    default:
      return { title: "Aegis · Approval needed", body: "A device is waiting for you to confirm." };
  }
}

/**
 * Mint a signed nonce, INSERT it into `push_nonces`, then fan out a
 * WebPush to every subscription the user owns. The DB insert happens
 * from a secure server context so we don't need a client INSERT policy
 * on `push_nonces` — RLS keeps it read/update only.
 */
export const requestApproval = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d) => RequestInput.parse(d))
  .handler(async ({ data, context }) => {
    const { userId } = context;
    const secret = requireNonceSecret();

    // Load service-role client only inside the handler — see server-side-modern.
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

    // 1. Load the user's push subscriptions.
    const { data: subs, error: subErr } = await supabaseAdmin
      .from("push_subscriptions")
      .select("endpoint, p256dh, auth")
      .eq("user_id", userId);
    if (subErr) throw new Error(subErr.message);

    // 2. Insert nonce row (id generated by the DB, then we sign it and
    //    UPDATE the signature back — two-step so `id` is part of the
    //    signed material without an extra client-side UUID).
    const expiresAtMs = Date.now() + (data.ttlMs ?? DEFAULT_NONCE_TTL_MS);
    const expiresAtIso = new Date(expiresAtMs).toISOString();
    const { data: inserted, error: insErr } = await supabaseAdmin
      .from("push_nonces")
      .insert({
        user_id: userId,
        action: data.action,
        payload: data.payload as Record<string, unknown> as never,
        signature: "pending",
        expires_at: expiresAtIso,
      })
      .select("id")
      .single();
    if (insErr || !inserted) throw new Error(insErr?.message ?? "insert failed");

    const material: NonceMaterial = {
      id: inserted.id,
      userId,
      action: data.action,
      expiresAt: expiresAtMs,
      payload: data.payload,
    };
    const signature = await signNonce(material, secret);

    const { error: sigErr } = await supabaseAdmin
      .from("push_nonces")
      .update({ signature })
      .eq("id", inserted.id);
    if (sigErr) throw new Error(sigErr.message);

    // 3. Fan out WebPush (best-effort — nonce is valid regardless).
    const { sendApprovalPush } = await import("@/lib/push-sender.server");
    const msg = approvalMessage(data.action);
    const push = await sendApprovalPush({
      subscriptions: (subs ?? []).map((s) => ({
        endpoint: s.endpoint,
        p256dh: s.p256dh,
        auth: s.auth,
      })),
      message: {
        title: msg.title,
        body: msg.body,
        url: `/approve?nonce=${encodeURIComponent(inserted.id)}`,
        nonceId: inserted.id,
      },
    });

    // 4. Prune subscriptions the push service reported as gone.
    if (push.ok && push.goneEndpoints.length > 0) {
      await supabaseAdmin
        .from("push_subscriptions")
        .delete()
        .in("endpoint", push.goneEndpoints);
    }

    return {
      ok: true as const,
      nonceId: inserted.id,
      expiresAt: expiresAtIso,
      push: push.ok
        ? { delivered: push.delivered, failed: push.failed }
        : { delivered: 0, failed: 0, reason: push.reason },
    };
  });

/* --------------------------------------------------------------------- */
/*  Consume nonce                                                        */
/* --------------------------------------------------------------------- */

const ConsumeInput = z.object({ nonceId: z.string().uuid() });

export const consumePushNonce = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d) => ConsumeInput.parse(d))
  .handler(async ({ data, context }) => {
    const { supabase, userId } = context;
    const secret = requireNonceSecret();

    const { data: row, error } = await supabase
      .from("push_nonces")
      .select("id, user_id, action, payload, signature, expires_at, consumed_at")
      .eq("id", data.nonceId)
      .maybeSingle();
    if (error) throw new Error(error.message);
    if (!row) return { ok: false as const, reason: "not_found" as const };
    if (row.user_id !== userId) return { ok: false as const, reason: "forbidden" as const };
    if (row.consumed_at) return { ok: false as const, reason: "already_consumed" as const };

    const expiresAtMs = new Date(row.expires_at).getTime();
    const material: NonceMaterial = {
      id: row.id,
      userId: row.user_id,
      action: row.action,
      expiresAt: expiresAtMs,
      payload: row.payload,
    };
    const verified = await verifyNonce(material, row.signature, secret);
    if (!verified.ok) return { ok: false as const, reason: verified.reason } as const;

    // Mark consumed. RLS restricts to own + unconsumed rows.
    const { error: updErr } = await supabase
      .from("push_nonces")
      .update({ consumed_at: new Date().toISOString() })
      .eq("id", row.id);
    if (updErr) throw new Error(updErr.message);

    return {
      ok: true as const,
      action: row.action,
      payload: row.payload,
    };
  });
