/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevTokensRouteImport } from './routes/dev.tokens'
import { Route as BlogGoogleAuthenticatorForPcRouteImport } from './routes/blog.google-authenticator-for-pc'
import { Route as BlogAegisVsGoogleAuthenticatorRouteImport } from './routes/blog.aegis-vs-google-authenticator'
import { Route as BlogAegisVsAuthyRouteImport } from './routes/blog.aegis-vs-authy'
import { Route as AuthResetPasswordRouteImport } from './routes/auth_.reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLockRouteImport } from './routes/_authenticated/lock'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated/emergency'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedApproveRouteImport } from './routes/_authenticated/approve'
import { Route as AuthenticatedTabsRouteImport } from './routes/_authenticated/_tabs'
import { Route as AuthenticatedLockedRouteRouteImport } from './routes/_authenticated/_locked/route'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedTabsVaultRouteImport } from './routes/_authenticated/_tabs/vault'
import { Route as AuthenticatedTabsSecurityRouteImport } from './routes/_authenticated/_tabs/security'
import { Route as AuthenticatedTabsProfileRouteImport } from './routes/_authenticated/_tabs/profile'
import { Route as AuthenticatedLockedVaultRecoveryRouteImport } from './routes/_authenticated/_locked/vault_.recovery'
import { Route as AuthenticatedLockedVaultNewRouteImport } from './routes/_authenticated/_locked/vault_.new'
import { Route as AuthenticatedLockedVaultImportRouteImport } from './routes/_authenticated/_locked/vault_.import'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTokensRoute = DevTokensRouteImport.update({
  id: '/dev/tokens',
  path: '/dev/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogGoogleAuthenticatorForPcRoute =
  BlogGoogleAuthenticatorForPcRouteImport.update({
    id: '/blog/google-authenticator-for-pc',
    path: '/blog/google-authenticator-for-pc',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAegisVsGoogleAuthenticatorRoute =
  BlogAegisVsGoogleAuthenticatorRouteImport.update({
    id: '/blog/aegis-vs-google-authenticator',
    path: '/blog/aegis-vs-google-authenticator',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAegisVsAuthyRoute = BlogAegisVsAuthyRouteImport.update({
  id: '/blog/aegis-vs-authy',
  path: '/blog/aegis-vs-authy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth_/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLockRoute = AuthenticatedLockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApproveRoute = AuthenticatedApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTabsRoute = AuthenticatedTabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLockedRouteRoute =
  AuthenticatedLockedRouteRouteImport.update({
    id: '/_locked',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTabsVaultRoute = AuthenticatedTabsVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedTabsRoute,
} as any)
const AuthenticatedTabsSecurityRoute =
  AuthenticatedTabsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedTabsRoute,
  } as any)
const AuthenticatedTabsProfileRoute =
  AuthenticatedTabsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedTabsRoute,
  } as any)
const AuthenticatedLockedVaultRecoveryRoute =
  AuthenticatedLockedVaultRecoveryRouteImport.update({
    id: '/vault_/recovery',
    path: '/vault/recovery',
    getParentRoute: () => AuthenticatedLockedRouteRoute,
  } as any)
const AuthenticatedLockedVaultNewRoute =
  AuthenticatedLockedVaultNewRouteImport.update({
    id: '/vault_/new',
    path: '/vault/new',
    getParentRoute: () => AuthenticatedLockedRouteRoute,
  } as any)
const AuthenticatedLockedVaultImportRoute =
  AuthenticatedLockedVaultImportRouteImport.update({
    id: '/vault_/import',
    path: '/vault/import',
    getParentRoute: () => AuthenticatedLockedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/approve': typeof AuthenticatedApproveRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/lock': typeof AuthenticatedLockRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/aegis-vs-authy': typeof BlogAegisVsAuthyRoute
  '/blog/aegis-vs-google-authenticator': typeof BlogAegisVsGoogleAuthenticatorRoute
  '/blog/google-authenticator-for-pc': typeof BlogGoogleAuthenticatorForPcRoute
  '/dev/tokens': typeof DevTokensRoute
  '/profile': typeof AuthenticatedTabsProfileRoute
  '/security': typeof AuthenticatedTabsSecurityRoute
  '/vault': typeof AuthenticatedTabsVaultRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/vault/import': typeof AuthenticatedLockedVaultImportRoute
  '/vault/new': typeof AuthenticatedLockedVaultNewRoute
  '/vault/recovery': typeof AuthenticatedLockedVaultRecoveryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/approve': typeof AuthenticatedApproveRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/lock': typeof AuthenticatedLockRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/aegis-vs-authy': typeof BlogAegisVsAuthyRoute
  '/blog/aegis-vs-google-authenticator': typeof BlogAegisVsGoogleAuthenticatorRoute
  '/blog/google-authenticator-for-pc': typeof BlogGoogleAuthenticatorForPcRoute
  '/dev/tokens': typeof DevTokensRoute
  '/profile': typeof AuthenticatedTabsProfileRoute
  '/security': typeof AuthenticatedTabsSecurityRoute
  '/vault': typeof AuthenticatedTabsVaultRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/vault/import': typeof AuthenticatedLockedVaultImportRoute
  '/vault/new': typeof AuthenticatedLockedVaultNewRoute
  '/vault/recovery': typeof AuthenticatedLockedVaultRecoveryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/_locked': typeof AuthenticatedLockedRouteRouteWithChildren
  '/_authenticated/_tabs': typeof AuthenticatedTabsRouteWithChildren
  '/_authenticated/approve': typeof AuthenticatedApproveRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/lock': typeof AuthenticatedLockRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/auth_/reset-password': typeof AuthResetPasswordRoute
  '/blog/aegis-vs-authy': typeof BlogAegisVsAuthyRoute
  '/blog/aegis-vs-google-authenticator': typeof BlogAegisVsGoogleAuthenticatorRoute
  '/blog/google-authenticator-for-pc': typeof BlogGoogleAuthenticatorForPcRoute
  '/dev/tokens': typeof DevTokensRoute
  '/_authenticated/_tabs/profile': typeof AuthenticatedTabsProfileRoute
  '/_authenticated/_tabs/security': typeof AuthenticatedTabsSecurityRoute
  '/_authenticated/_tabs/vault': typeof AuthenticatedTabsVaultRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/_locked/vault_/import': typeof AuthenticatedLockedVaultImportRoute
  '/_authenticated/_locked/vault_/new': typeof AuthenticatedLockedVaultNewRoute
  '/_authenticated/_locked/vault_/recovery': typeof AuthenticatedLockedVaultRecoveryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/approve'
    | '/devices'
    | '/emergency'
    | '/family'
    | '/lock'
    | '/onboarding'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/blog/aegis-vs-authy'
    | '/blog/aegis-vs-google-authenticator'
    | '/blog/google-authenticator-for-pc'
    | '/dev/tokens'
    | '/profile'
    | '/security'
    | '/vault'
    | '/api/public/health'
    | '/api/public/stripe-webhook'
    | '/vault/import'
    | '/vault/new'
    | '/vault/recovery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/approve'
    | '/devices'
    | '/emergency'
    | '/family'
    | '/lock'
    | '/onboarding'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/blog/aegis-vs-authy'
    | '/blog/aegis-vs-google-authenticator'
    | '/blog/google-authenticator-for-pc'
    | '/dev/tokens'
    | '/profile'
    | '/security'
    | '/vault'
    | '/api/public/health'
    | '/api/public/stripe-webhook'
    | '/vault/import'
    | '/vault/new'
    | '/vault/recovery'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/_locked'
    | '/_authenticated/_tabs'
    | '/_authenticated/approve'
    | '/_authenticated/devices'
    | '/_authenticated/emergency'
    | '/_authenticated/family'
    | '/_authenticated/lock'
    | '/_authenticated/onboarding'
    | '/auth_/callback'
    | '/auth_/reset-password'
    | '/blog/aegis-vs-authy'
    | '/blog/aegis-vs-google-authenticator'
    | '/blog/google-authenticator-for-pc'
    | '/dev/tokens'
    | '/_authenticated/_tabs/profile'
    | '/_authenticated/_tabs/security'
    | '/_authenticated/_tabs/vault'
    | '/api/public/health'
    | '/api/public/stripe-webhook'
    | '/_authenticated/_locked/vault_/import'
    | '/_authenticated/_locked/vault_/new'
    | '/_authenticated/_locked/vault_/recovery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  BlogAegisVsAuthyRoute: typeof BlogAegisVsAuthyRoute
  BlogAegisVsGoogleAuthenticatorRoute: typeof BlogAegisVsGoogleAuthenticatorRoute
  BlogGoogleAuthenticatorForPcRoute: typeof BlogGoogleAuthenticatorForPcRoute
  DevTokensRoute: typeof DevTokensRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/tokens': {
      id: '/dev/tokens'
      path: '/dev/tokens'
      fullPath: '/dev/tokens'
      preLoaderRoute: typeof DevTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/google-authenticator-for-pc': {
      id: '/blog/google-authenticator-for-pc'
      path: '/blog/google-authenticator-for-pc'
      fullPath: '/blog/google-authenticator-for-pc'
      preLoaderRoute: typeof BlogGoogleAuthenticatorForPcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/aegis-vs-google-authenticator': {
      id: '/blog/aegis-vs-google-authenticator'
      path: '/blog/aegis-vs-google-authenticator'
      fullPath: '/blog/aegis-vs-google-authenticator'
      preLoaderRoute: typeof BlogAegisVsGoogleAuthenticatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/aegis-vs-authy': {
      id: '/blog/aegis-vs-authy'
      path: '/blog/aegis-vs-authy'
      fullPath: '/blog/aegis-vs-authy'
      preLoaderRoute: typeof BlogAegisVsAuthyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/reset-password': {
      id: '/auth_/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lock': {
      id: '/_authenticated/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof AuthenticatedLockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approve': {
      id: '/_authenticated/approve'
      path: '/approve'
      fullPath: '/approve'
      preLoaderRoute: typeof AuthenticatedApproveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_tabs': {
      id: '/_authenticated/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedTabsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_locked': {
      id: '/_authenticated/_locked'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLockedRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_tabs/vault': {
      id: '/_authenticated/_tabs/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedTabsVaultRouteImport
      parentRoute: typeof AuthenticatedTabsRoute
    }
    '/_authenticated/_tabs/security': {
      id: '/_authenticated/_tabs/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedTabsSecurityRouteImport
      parentRoute: typeof AuthenticatedTabsRoute
    }
    '/_authenticated/_tabs/profile': {
      id: '/_authenticated/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedTabsProfileRouteImport
      parentRoute: typeof AuthenticatedTabsRoute
    }
    '/_authenticated/_locked/vault_/recovery': {
      id: '/_authenticated/_locked/vault_/recovery'
      path: '/vault/recovery'
      fullPath: '/vault/recovery'
      preLoaderRoute: typeof AuthenticatedLockedVaultRecoveryRouteImport
      parentRoute: typeof AuthenticatedLockedRouteRoute
    }
    '/_authenticated/_locked/vault_/new': {
      id: '/_authenticated/_locked/vault_/new'
      path: '/vault/new'
      fullPath: '/vault/new'
      preLoaderRoute: typeof AuthenticatedLockedVaultNewRouteImport
      parentRoute: typeof AuthenticatedLockedRouteRoute
    }
    '/_authenticated/_locked/vault_/import': {
      id: '/_authenticated/_locked/vault_/import'
      path: '/vault/import'
      fullPath: '/vault/import'
      preLoaderRoute: typeof AuthenticatedLockedVaultImportRouteImport
      parentRoute: typeof AuthenticatedLockedRouteRoute
    }
  }
}

interface AuthenticatedLockedRouteRouteChildren {
  AuthenticatedLockedVaultImportRoute: typeof AuthenticatedLockedVaultImportRoute
  AuthenticatedLockedVaultNewRoute: typeof AuthenticatedLockedVaultNewRoute
  AuthenticatedLockedVaultRecoveryRoute: typeof AuthenticatedLockedVaultRecoveryRoute
}

const AuthenticatedLockedRouteRouteChildren: AuthenticatedLockedRouteRouteChildren =
  {
    AuthenticatedLockedVaultImportRoute: AuthenticatedLockedVaultImportRoute,
    AuthenticatedLockedVaultNewRoute: AuthenticatedLockedVaultNewRoute,
    AuthenticatedLockedVaultRecoveryRoute:
      AuthenticatedLockedVaultRecoveryRoute,
  }

const AuthenticatedLockedRouteRouteWithChildren =
  AuthenticatedLockedRouteRoute._addFileChildren(
    AuthenticatedLockedRouteRouteChildren,
  )

interface AuthenticatedTabsRouteChildren {
  AuthenticatedTabsProfileRoute: typeof AuthenticatedTabsProfileRoute
  AuthenticatedTabsSecurityRoute: typeof AuthenticatedTabsSecurityRoute
  AuthenticatedTabsVaultRoute: typeof AuthenticatedTabsVaultRoute
}

const AuthenticatedTabsRouteChildren: AuthenticatedTabsRouteChildren = {
  AuthenticatedTabsProfileRoute: AuthenticatedTabsProfileRoute,
  AuthenticatedTabsSecurityRoute: AuthenticatedTabsSecurityRoute,
  AuthenticatedTabsVaultRoute: AuthenticatedTabsVaultRoute,
}

const AuthenticatedTabsRouteWithChildren =
  AuthenticatedTabsRoute._addFileChildren(AuthenticatedTabsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLockedRouteRoute: typeof AuthenticatedLockedRouteRouteWithChildren
  AuthenticatedTabsRoute: typeof AuthenticatedTabsRouteWithChildren
  AuthenticatedApproveRoute: typeof AuthenticatedApproveRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedLockRoute: typeof AuthenticatedLockRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLockedRouteRoute: AuthenticatedLockedRouteRouteWithChildren,
  AuthenticatedTabsRoute: AuthenticatedTabsRouteWithChildren,
  AuthenticatedApproveRoute: AuthenticatedApproveRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedLockRoute: AuthenticatedLockRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  BlogAegisVsAuthyRoute: BlogAegisVsAuthyRoute,
  BlogAegisVsGoogleAuthenticatorRoute: BlogAegisVsGoogleAuthenticatorRoute,
  BlogGoogleAuthenticatorForPcRoute: BlogGoogleAuthenticatorForPcRoute,
  DevTokensRoute: DevTokensRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
